-- Fix Apollo product names: restore true product types/variants per March 2026 price list
-- Keyed by Item Code stored in specs. Safe to re-run.
BEGIN;
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Plastic Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02080V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Plastic Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02100V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Elbow Brass Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02200V';
UPDATE public.products SET name = 'Apollo CPVC-X Tee 1/2" (15mm)' WHERE specs->>'Item Code' = 'CMN02040V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Tee Brass Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02220V';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Plastic Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02080W';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Plastic Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02100W';
UPDATE public.products SET name = 'Apollo CPVC-X Female Elbow Brass Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02200W';
UPDATE public.products SET name = 'Apollo CPVC-X Tee 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02040W';
UPDATE public.products SET name = 'Apollo CPVC-X Female Tee Brass Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02220W';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Plastic Threaded 1" (25mm)' WHERE specs->>'Item Code' = 'CMN020801';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Plastic Threaded 1" (25mm)' WHERE specs->>'Item Code' = 'CMN021001';
UPDATE public.products SET name = 'Apollo CPVC-X Reducing Female Elbow Brass Threaded 3/4"x1/2" (20x15mm)' WHERE specs->>'Item Code' = 'CMN02210W0V';
UPDATE public.products SET name = 'Apollo CPVC-X Mixer Adaptor 3/4"x1/2" (20x15mm)' WHERE specs->>'Item Code' = 'CM02350W0V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Brass Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02180V';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Brass Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'CM02160V';
UPDATE public.products SET name = 'Apollo CPVC-X Reducing Female Elbow Brass Threaded 1"x1/2" (25x15mm)' WHERE specs->>'Item Code' = 'CMN0221010W';
UPDATE public.products SET name = 'Apollo CPVC-X Mixer Adaptor 1"x1/2" (25x15mm)' WHERE specs->>'Item Code' = 'CM0235010V';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Brass Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02160W';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Brass Threaded 3/4" (20mm)' WHERE specs->>'Item Code' = 'CMN02180W';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor With Hexaganol Brass Inserts 1"x1" (25x25mm)' WHERE specs->>'Item Code' = 'CM023101';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor With Hexaganol Brass Inserts 1"x1" (25x25mm)' WHERE specs->>'Item Code' = 'CM023301';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Plastic Threaded 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'CMN02102V';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Plastic Threaded 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'CM02082V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor With Hexaganol Brass Inserts 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'CM02332V';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Brass Threaded 1" (25mm)' WHERE specs->>'Item Code' = 'CMN02181U';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Brass Threaded 1" (25mm)' WHERE specs->>'Item Code' = 'CMN021601';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor With Hexaganol Brass Inserts 1-1/4"x1-1/4" (32x32mm)' WHERE specs->>'Item Code' = 'CM02311U';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor With Hexaganol Brass Inserts 1-1/4"x1-1/4" (32x32mm)' WHERE specs->>'Item Code' = 'CM02331U';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor Plastic Threaded 3" (80mm)' WHERE specs->>'Item Code' = 'CMN021003';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor Plastic Threaded 3" (80mm)' WHERE specs->>'Item Code' = 'CMN020803';
UPDATE public.products SET name = 'Apollo CPVC-X Female Adaptor With Hexaganol Brass Inserts 3" (80mm)' WHERE specs->>'Item Code' = 'CM023303';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor With Hexaganol Brass Inserts 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'CM02312V';
UPDATE public.products SET name = 'Apollo CPVC-X Ball Valve 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'CTP02302V';
UPDATE public.products SET name = 'Apollo CPVC-X Male Adaptor With Hexaganol Brass Inserts 3" (80mm)' WHERE specs->>'Item Code' = 'CM023103';
UPDATE public.products SET name = 'Apollo CPVC-X Ball Valve 3" (80mm)' WHERE specs->>'Item Code' = 'CTP023003';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 6" (160mm)' WHERE specs->>'Item Code' = 'PMN032806';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 45 6" (160mm)' WHERE specs->>'Item Code' = 'PMNN033406';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn10 3/4" (20mm)' WHERE specs->>'Item Code' = 'PM03310V';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor Pn10 3/4" (20mm)' WHERE specs->>'Item Code' = 'PM03220V';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor Pn10 3/4" (20mm)' WHERE specs->>'Item Code' = 'PM03250V';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn10 1" (25mm)' WHERE specs->>'Item Code' = 'PM03310W';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor Pn10 1" (25mm)' WHERE specs->>'Item Code' = 'PM03220W';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor Pn10 1" (25mm)' WHERE specs->>'Item Code' = 'PM03250W';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn10 1-1/4" (32mm)' WHERE specs->>'Item Code' = 'PM033101';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor Pn10 1-1/4" (32mm)' WHERE specs->>'Item Code' = 'PM032201';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 1-1/4" (32mm)' WHERE specs->>'Item Code' = 'PM031101';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor (Mta) Pn6 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PM03121U';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn6 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PM03211U';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PMN03111U';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Plastic Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'UM01060V';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Plastic Threaded 1/2" (15mm)' WHERE specs->>'Item Code' = 'UM01070V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Rubber Ring (Yellow) Extra 3" (75mm)' WHERE specs->>'Item Code' = 'PM03462V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Door Cap 3" (75mm)' WHERE specs->>'Item Code' = 'PM03412V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Coupler 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03612V';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03282V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Coupler 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03312V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 45 3" (75mm)' WHERE specs->>'Item Code' = 'PT01092V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 87.5 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03632V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 87.5 (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03642V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Cleaning Pipe (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03492V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Y 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03372V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Y (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03382V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Double Y 3" (75mm)' WHERE specs->>'Item Code' = 'PT01202V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 45 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03652V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Double Tee 4" (110mm)' WHERE specs->>'Item Code' = 'PM03920404';
UPDATE public.products SET name = 'Apollo SWR Jali Round 4" (110mm)' WHERE specs->>'Item Code' = 'PMN032304';
UPDATE public.products SET name = 'Apollo SWR Vent Cowl 4" (110mm)' WHERE specs->>'Item Code' = 'PMN31404';
UPDATE public.products SET name = 'Apollo SWR Pipe Clamp 4" (110mm)' WHERE specs->>'Item Code' = 'PMN31304';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 4" (110mm)' WHERE specs->>'Item Code' = 'PMN030404';
UPDATE public.products SET name = 'Apollo SWR Multi Floor Trap (Without Jali) 4" (110mm)' WHERE specs->>'Item Code' = 'PMN032404';
UPDATE public.products SET name = 'Apollo SWR Tee 4KG/CM2 W/o Collar Extra Strong 4" (110mm)' WHERE specs->>'Item Code' = 'PM038504';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 4" (110mm)' WHERE specs->>'Item Code' = 'PMN030604';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Off Set Bend 4" (110mm)' WHERE specs->>'Item Code' = 'PMN037204';
UPDATE public.products SET name = 'Apollo SWR Tee Pn10 4" (110mm)' WHERE specs->>'Item Code' = 'PMN37404';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PMN03011U';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PMN03031U';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PM03281U';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 45 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PT01081U';
UPDATE public.products SET name = 'Apollo SWR Ringfit Rubber Ring (Yellow) Extra 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PM034603';
UPDATE public.products SET name = 'Apollo SWR Ringfit Door Cap 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PM034103';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN32803';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Coupler 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN036103';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 45 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN033403';
UPDATE public.products SET name = 'Apollo SWR Ringfit Coupler 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN033103';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 87.5 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN036303';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 87.5 (With Door) 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN036403';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Y 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PT011503';
UPDATE public.products SET name = 'Apollo SWR Vent Cowl 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN31402';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN030402';
UPDATE public.products SET name = 'Apollo SWR Tee 4KG/CM2 W/o Collar Extra Strong 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PM038502';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PM030602';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PMN03041U';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 1-1/2" (40mm)' WHERE specs->>'Item Code' = 'PMN03061U';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn6 2" (50mm)' WHERE specs->>'Item Code' = 'PM03211V';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 2" (50mm)' WHERE specs->>'Item Code' = 'PMN03111V';
UPDATE public.products SET name = 'Apollo SWR Vent Cowl 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03142V';
UPDATE public.products SET name = 'Apollo SWR Pipe Clamp 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03122V';
UPDATE public.products SET name = 'Apollo SWR Tee Regular 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03052V';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03042V';
UPDATE public.products SET name = 'Apollo SWR Tee 4KG/CM2 W/o Collar Extra Strong 3" (75mm)' WHERE specs->>'Item Code' = 'PM03852V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Tee 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03682V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Cleaning Pipe (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03762V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Tee 3" (75mm)' WHERE specs->>'Item Code' = 'PMNN03422V';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03062V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Tee (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03692V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Y 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03662V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Tee (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMNN03432V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Off Set Bend 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03722V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Y (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03672V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Double Tee 3" (75mm)' WHERE specs->>'Item Code' = 'PT01102V';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn4 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN32102';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn6 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN32902';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor (Mta) Pn6 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN31202';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN31102';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 2" (50mm)' WHERE specs->>'Item Code' = 'PMN03011V';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 2" (50mm)' WHERE specs->>'Item Code' = 'PMN03031V';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 2" (50mm)' WHERE specs->>'Item Code' = 'PM03281V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 45 2" (50mm)' WHERE specs->>'Item Code' = 'PT01091V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 45 2" (50mm)' WHERE specs->>'Item Code' = 'PT01081V';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector Short 1/2" (15mm)' WHERE specs->>'Item Code' = 'UM01170V';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector (Long) 1/2" (15mm)' WHERE specs->>'Item Code' = 'UM01240V';
UPDATE public.products SET name = 'Apollo SWR Pipe Clamp 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN31303';
UPDATE public.products SET name = 'Apollo SWR Vent Cowl 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN31403';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030403';
UPDATE public.products SET name = 'Apollo SWR Tee Regular 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030503';
UPDATE public.products SET name = 'Apollo SWR Tee 4KG/CM2 W/o Collar Extra Strong 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PM038503';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030603';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Tee 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN036803';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Tee 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN034203';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Tee (With Door) 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN036903';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Y 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PT011603';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Tee (With Door) 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN034303';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Off Set Bend 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN037203';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Single Y (With Door) 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PT011703';
UPDATE public.products SET name = 'Apollo SWR Tee Pn10 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN37403';
UPDATE public.products SET name = 'Apollo SWR Ringfit Double Tee 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PT011403';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn4 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03212V';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn6 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03292V';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03112V';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN030102';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PM030302';
UPDATE public.products SET name = 'Apollo SWR Tee Pn4 2" (50mm)' WHERE specs->>'Item Code' = 'PMN03041V';
UPDATE public.products SET name = 'Apollo SWR Tee Pn6 Isi 2" (50mm)' WHERE specs->>'Item Code' = 'PMN03061V';
UPDATE public.products SET name = 'Apollo SWR Elbow Regular 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03022V';
UPDATE public.products SET name = 'Apollo SWR Elbow 4KG/CM W/o Collar Extra Strong 3" (75mm)' WHERE specs->>'Item Code' = 'PM039602';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector Short 3/4" (20mm)' WHERE specs->>'Item Code' = 'UM01170W';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector (Long) 3/4" (20mm)' WHERE specs->>'Item Code' = 'UM01240W';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PMN32802';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Bend 45 2-1/2" (63mm)' WHERE specs->>'Item Code' = 'PT010802';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn4 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN32103';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor (Mta) Pn6 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN31203';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN031103';
UPDATE public.products SET name = 'Apollo SWR Reducing Coupler 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0308042V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Coupler 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0362042V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Coupler 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0335042V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Tee 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03450604';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Tee 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03700604';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Tee (With Door) 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03710604';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Tee (With Door) 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03360604';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03012V';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03032V';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector Short 1" (25mm)' WHERE specs->>'Item Code' = 'UM011701';
UPDATE public.products SET name = 'Apollo uPVC Tank Connector (Long) 1" (25mm)' WHERE specs->>'Item Code' = 'UM012401';
UPDATE public.products SET name = 'Apollo SWR Tail Piece Grey 3" (75mm)' WHERE specs->>'Item Code' = 'PT01062V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 87.5 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03322V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 87.5 (With Door) 3" (75mm)' WHERE specs->>'Item Code' = 'PMN03332V';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn4 4" (110mm)' WHERE specs->>'Item Code' = 'PMN032104';
UPDATE public.products SET name = 'Apollo SWR Male Threaded Adaptor (Mta) Pn6 4" (110mm)' WHERE specs->>'Item Code' = 'PMN031204';
UPDATE public.products SET name = 'Apollo SWR Female Threaded Adaptor (Fta) Pn6 4" (110mm)' WHERE specs->>'Item Code' = 'PMN031104';
UPDATE public.products SET name = 'Apollo SWR Elbow Regular 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030203';
UPDATE public.products SET name = 'Apollo SWR Elbow 4KG/CM W/o Collar Extra Strong 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PM03962V';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030103';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN030303';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn10 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN37303';
UPDATE public.products SET name = 'Apollo SWR Reducing Coupler 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03080604';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Coupler 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03620604';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Coupler 6"x4" (160x110mm)' WHERE specs->>'Item Code' = 'PMN03350604';
UPDATE public.products SET name = 'Apollo SWR Tail Piece Grey 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PT010603';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 87.5 (With Door) 3-1/2" (90mm)' WHERE specs->>'Item Code' = 'PMN033303';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 1/2"x1/2" (15x15mm)' WHERE specs->>'Item Code' = 'UMN01140V';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 1/2"x1/2" (15x15mm)' WHERE specs->>'Item Code' = 'UMN01130V';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 3/4"x1/2" (20x15mm)' WHERE specs->>'Item Code' = 'UMN01140W0V';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 3/4"x1/2" (20x15mm)' WHERE specs->>'Item Code' = 'UMN01130W0V';
UPDATE public.products SET name = 'Apollo SWR Elbow Regular 4" (110mm)' WHERE specs->>'Item Code' = 'PMN030204';
UPDATE public.products SET name = 'Apollo SWR Elbow 4KG/CM W/o Collar Extra Strong 4" (110mm)' WHERE specs->>'Item Code' = 'PM039603';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn4 4" (110mm)' WHERE specs->>'Item Code' = 'PMN030104';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn6 Isi 4" (110mm)' WHERE specs->>'Item Code' = 'PMN030304';
UPDATE public.products SET name = 'Apollo SWR Elbow Pn10 4" (110mm)' WHERE specs->>'Item Code' = 'PMN37304';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 1"x1/2" (25X15mm)' WHERE specs->>'Item Code' = 'UMN01141V';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 1"x1/2" (25X15mm)' WHERE specs->>'Item Code' = 'UM0113010V';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Plastic Threaded 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01062V';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Plastic Threaded 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01072V';
UPDATE public.products SET name = 'Apollo SWR Vent Cowl 6" (160mm)' WHERE specs->>'Item Code' = 'PMN031406';
UPDATE public.products SET name = 'Apollo SWR Tee 6" (160mm)' WHERE specs->>'Item Code' = 'PMN030606';
UPDATE public.products SET name = 'Apollo uPVC Coupler 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01022V';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor With Hexaganol Brass Inserts 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01182V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Nahani Trap (Without Jali) 4"x2-1/2" (110x63mm)' WHERE specs->>'Item Code' = 'PMN03200402';
UPDATE public.products SET name = 'Apollo SWR Nahani Trap W/s (One Pc) 4"x2-1/2" (110x63mm)' WHERE specs->>'Item Code' = 'PM03890402';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 3/4"x3/4" (20x20mm)' WHERE specs->>'Item Code' = 'UMN01140W';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 3/4"x3/4" (20x20mm)' WHERE specs->>'Item Code' = 'UMN01130W';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Nahani Trap (Without Jali) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0320042V';
UPDATE public.products SET name = 'Apollo SWR Nahani Trap W/s (One Pc) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PM0389042V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Y (With Door) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PM0377042V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Y 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0373042V';
UPDATE public.products SET name = 'Apollo SWR Tail Piece Grey 4" (110mm)' WHERE specs->>'Item Code' = 'PT010604';
UPDATE public.products SET name = 'Apollo SWR Horn Shoe (With Door) 4" (110mm)' WHERE specs->>'Item Code' = 'PM038604';
UPDATE public.products SET name = 'Apollo SWR Coupler 6 Kg 4" (110mm)' WHERE specs->>'Item Code' = 'PMN32804';
UPDATE public.products SET name = 'Apollo SWR Ringfit Bend 45 4" (110mm)' WHERE specs->>'Item Code' = 'PMNN033404';
UPDATE public.products SET name = 'Apollo SWR Ringfit Horn Shoe (With Door) 4" (110mm)' WHERE specs->>'Item Code' = 'PM035104';
UPDATE public.products SET name = 'Apollo SWR Ringfit Single Y (With Door) 4" (110mm)' WHERE specs->>'Item Code' = 'PMNN033804';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Nahani Trap (Without Jali) 4"x3-1/2" (110x90mm)' WHERE specs->>'Item Code' = 'PMN03200403';
UPDATE public.products SET name = 'Apollo SWR Nahani Trap W/s (One Pc) 4"x3-1/2" (110x90mm)' WHERE specs->>'Item Code' = 'PM03890403';
UPDATE public.products SET name = 'Apollo uPVC Coupler 3" (80mm)' WHERE specs->>'Item Code' = 'UM010203';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor With Hexaganol Brass Inserts 3" (80mm)' WHERE specs->>'Item Code' = 'UM011804';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Plastic Threaded 3" (80mm)' WHERE specs->>'Item Code' = 'UM010603';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Plastic Threaded 3" (80mm)' WHERE specs->>'Item Code' = 'UM010703';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Nahani Trap (Without Jali) 4"x4" (110x110mm)' WHERE specs->>'Item Code' = 'PMN03200404';
UPDATE public.products SET name = 'Apollo SWR Nahani Trap W/s (One Pc) 4"x4" (110x110mm)' WHERE specs->>'Item Code' = 'PM03890404';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Tee 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0345042V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Tee 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0370042V';
UPDATE public.products SET name = 'Apollo SWR Reducing Tee Pn4 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0309042V';
UPDATE public.products SET name = 'Apollo SWR Self-Fit Reducing Tee (With Door) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN0371042V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Tee (With Door) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PMN036042V';
UPDATE public.products SET name = 'Apollo SWR Ringfit Reducing Y (With Door) 4"x3" (110x75mm)' WHERE specs->>'Item Code' = 'PM0350042V';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn4 6" (160mm)' WHERE specs->>'Item Code' = 'PMN32106';
UPDATE public.products SET name = 'Apollo SWR End Cap Pn6 6" (160mm)' WHERE specs->>'Item Code' = 'PT010506';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 1"x1" (25x25mm)' WHERE specs->>'Item Code' = 'UMN011401';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 1"x1" (25x25mm)' WHERE specs->>'Item Code' = 'UMN011301';
UPDATE public.products SET name = 'Apollo uPVC Tee 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01032V';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor With Hexaganol Brass Inserts 2-1/2" (65mm)' WHERE specs->>'Item Code' = 'UM01202V';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Plastic Threaded 4" (100mm)' WHERE specs->>'Item Code' = 'UM010704';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Plastic Threaded 4" (100mm)' WHERE specs->>'Item Code' = 'UM010604';
UPDATE public.products SET name = 'Apollo SWR P-trap 4"x4" (110x110mm)' WHERE specs->>'Item Code' = 'PMN03170404';
UPDATE public.products SET name = 'Apollo SWR Q-trap 4"x4" (110x110mm)' WHERE specs->>'Item Code' = 'PMN03180404';
UPDATE public.products SET name = 'Apollo SWR S-trap 4"x4" (110x110mm)' WHERE specs->>'Item Code' = 'PMN03190404';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 1-1/4"x1-1/4" (32x32mm)' WHERE specs->>'Item Code' = 'UMN01141U';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 1-1/4"x1-1/4" (32x32mm)' WHERE specs->>'Item Code' = 'UMN01131U';
UPDATE public.products SET name = 'Apollo uPVC Tee 3" (80mm)' WHERE specs->>'Item Code' = 'UM010303';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor With Hexaganol Brass Inserts 3" (80mm)' WHERE specs->>'Item Code' = 'UM012004';
UPDATE public.products SET name = 'Apollo SWR P-trap 5"x4" (125x110mm)' WHERE specs->>'Item Code' = 'PMN03174V04';
UPDATE public.products SET name = 'Apollo SWR Q-trap 5"x4" (125x110mm)' WHERE specs->>'Item Code' = 'PM03184V04';
UPDATE public.products SET name = 'Apollo SWR S-trap 5"x4" (125x110mm)' WHERE specs->>'Item Code' = 'PMN03194V04';
UPDATE public.products SET name = 'Apollo uPVC Female Adaptor Brass Threaded 2"x2" (50x50mm)' WHERE specs->>'Item Code' = 'UM011402';
UPDATE public.products SET name = 'Apollo uPVC Male Adaptor Brass Threaded 2"x2" (50x50mm)' WHERE specs->>'Item Code' = 'UMN011302';
-- Price fixes for zero-price rows (verified against March 2026 price list PDF)
UPDATE public.products SET price = 229 WHERE specs->>'Item Code' = 'UMN01220W' AND (price = 0 OR price IS NULL);
UPDATE public.products SET price = 307 WHERE specs->>'Item Code' = 'PMN032806' AND (price = 0 OR price IS NULL);
COMMIT;
