// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jcqqepifotecmrjdyeup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcXFlcGlmb3RlY21yamR5ZXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNTM5NTYsImV4cCI6MjA4OTgyOTk1Nn0.gVdIG_60RwYWhq6t1A1wFkaMKgwa2BQ3-G4bZxLJSdE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);